declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'
  export const Menu: FC<SVGProps<SVGSVGElement>>
  export const X: FC<SVGProps<SVGSVGElement>>
  export const Phone: FC<SVGProps<SVGSVGElement>>
  export const MapPin: FC<SVGProps<SVGSVGElement>>
  export const ArrowDown: FC<SVGProps<SVGSVGElement>>
  export const Shield: FC<SVGProps<SVGSVGElement>>
  export const TrendingUp: FC<SVGProps<SVGSVGElement>>
  export const ChevronRight: FC<SVGProps<SVGSVGElement>>
  export const RotateCcw: FC<SVGProps<SVGSVGElement>>
  export const Home: FC<SVGProps<SVGSVGElement>>
  export const Building: FC<SVGProps<SVGSVGElement>>
  export const Calendar: FC<SVGProps<SVGSVGElement>>
  export const CheckCircle: FC<SVGProps<SVGSVGElement>>
  export const ArrowUpRight: FC<SVGProps<SVGSVGElement>>
  export const SlidersHorizontal: FC<SVGProps<SVGSVGElement>>
  export const Calculator: FC<SVGProps<SVGSVGElement>>
  export const Wallet: FC<SVGProps<SVGSVGElement>>
  export const Ruler: FC<SVGProps<SVGSVGElement>>
  export const Fence: FC<SVGProps<SVGSVGElement>>
  export const Clock: FC<SVGProps<SVGSVGElement>>
  export const BookOpen: FC<SVGProps<SVGSVGElement>>
  export const Send: FC<SVGProps<SVGSVGElement>>
  export const Instagram: FC<SVGProps<SVGSVGElement>>
  export const Facebook: FC<SVGProps<SVGSVGElement>>
  export const Globe: FC<SVGProps<SVGSVGElement>>
  export const Mail: FC<SVGProps<SVGSVGElement>>
  export const ExternalLink: FC<SVGProps<SVGSVGElement>>
  export const Check: FC<SVGProps<SVGSVGElement>>
  export const User: FC<SVGProps<SVGSVGElement>>
  export const MessageCircle: FC<SVGProps<SVGSVGElement>>
  export const ArrowLeft: FC<SVGProps<SVGSVGElement>>
  export const ChevronLeft: FC<SVGProps<SVGSVGElement>>
  export const HelpCircle: FC<SVGProps<SVGSVGElement>>
  export const Lock: FC<SVGProps<SVGSVGElement>>
  export const Eye: FC<SVGProps<SVGSVGElement>>
  export const EyeOff: FC<SVGProps<SVGSVGElement>>
  export const Users: FC<SVGProps<SVGSVGElement>>
  export const Search: FC<SVGProps<SVGSVGElement>>
  export const Filter: FC<SVGProps<SVGSVGElement>>
  export const LogOut: FC<SVGProps<SVGSVGElement>>
  export const AlertCircle: FC<SVGProps<SVGSVGElement>>
  export const MessageSquare: FC<SVGProps<SVGSVGElement>>
  export const Bell: FC<SVGProps<SVGSVGElement>>
  export const Zap: FC<SVGProps<SVGSVGElement>>
  export const Star: FC<SVGProps<SVGSVGElement>>
}